language: c

dist: precise
sudo: false

env:
  - ARCH=i386
  - ARCH=microblaze
  - ARCH=mips
  #- ARCH=msp430 # probably needs update
  - ARCH=powerpc
  - ARCH=sparc

addons:
  apt:
    packages:
      - gcc-multilib # otherwise gcc build fails during zlib stage
      - texinfo # for gdb docs

script:
  - "./crosstool.sh $ARCH > crosstool.log" #redirect stdout to avoid travis log limit

deploy:
  provider: releases
  api_key:
    secure: e63+ZkWZ+1Ms8+vIU1rz04jlS5loprVSQRwNmmey7ohZ4ybksVhAVEdKDX5x84+uoO4wkXJZ5XWNWr25RpXz/os0+vo1DJPYqwSvZfcuHxDNOOh/JKf+lSNC4gu0ZmUJkhyCcZbiuwNsnRuMBz7jYMuReE/C8Pg/c7XxbTaD3sdTHtafMJVEl+RGV94Jo9KS6WQVB5fZIqh8Qw3n9jpEveZJbfLp4uZnKo1tA9Yd18fQmCbvS2EoTyviaPs91sbG8k3vo+LM0Ny1YZhe+xWa7A8Z5wOjicPQsj1uaZJRkEJc0P5tdHItD+0XyJFUY/XJyLiPJjctkOE+PmPxk1NH/zEi2ThYvS0OVtG3a+Eeef61wvlfhgHY8gAMD+LuK1SQFHHwHzBFvRBoUgmIb03NnhyVPqffRoFtbXkECDo3WVB+8U0FgAtLS0HD8hgFffG3cqVm9nA4SGMVUThNOYFErbezM9EiAkR4vEO0na5Yd/FkZ9Vv2BbRy5ISXmH6VaqoQ/qFFsCvbAc/lkOdV1e6llSf7JD5/G5BeBIOGx2lArum6WWpCBDCFliPIARivxrlz9boxGRfMfiGZhJcJZDpzgy8mKcNxdA2980BvzwkPp6uv0zIwhS7ZPnn+y/ZruFcAJV34BPju7sdDzpu6oRKO/nNNuTpVH1qfj1UIqhqJ8I=
  file_glob: true
  file: "*-toolchain.tar.bz2"
  skip_cleanup: true
  on:
    repo: embox/crosstool
    tags: true
    overwrite: true
